apiVersion: confluentcloud.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: ccloud-creds
      namespace: crossplane-system
      key: credentials
